import { Platform, StatusBar, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 30,
  },
  saudacao: {
    fontSize: 16,
    color: "#666666",
    fontFamily: "Merriweather_Regular",
    marginBottom: 4,
  },
  nomeUsuario: {
    fontSize: 26,
    fontFamily: "Merriweather_Bold",
    color: "#4A729A",
  },
  perfilBotao: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  banner: {
    backgroundColor: "#4A729A",
    borderRadius: 20,
    padding: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 30,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  bannerTextContainer: {
    flex: 1,
    paddingRight: 16,
  },
  bannerTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontFamily: "Merriweather_Bold",
    marginBottom: 8,
  },
  bannerSubtitle: {
    color: "#E2E8F0",
    fontSize: 14,
    fontFamily: "Merriweather_Regular",
    lineHeight: 20,
    marginBottom: 16,
  },
  bannerButton: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  bannerButtonText: {
    color: "#4A729A",
    fontFamily: "Merriweather_Bold",
    fontSize: 14,
  },
  bannerImagePlaceholder: {
    width: 80,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: "Merriweather_Bold",
    color: "#333333",
    marginBottom: 16,
  },
  quickAccessRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 32,
  },
  quickAccessCard: {
    backgroundColor: "#FFFFFF",
    width: "30%",
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  quickAccessIconBox: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F0F4F8",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  quickAccessText: {
    fontSize: 13,
    fontFamily: "Merriweather_Bold",
    color: "#4A729A",
  },
  historyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 30,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  historyType: {
    fontSize: 14,
    fontFamily: "Merriweather_Bold",
    color: "#4A729A",
  },
  historyDate: {
    fontSize: 12,
    color: "#999999",
    fontFamily: "Merriweather_Regular",
  },
  historyTitle: {
    fontSize: 16,
    fontFamily: "Merriweather_Bold",
    color: "#333333",
    marginBottom: 4,
  },
  historySubtitle: {
    fontSize: 14,
    color: "#666666",
    fontFamily: "Merriweather_Regular",
  },
  cardUltimo: {
    backgroundColor: "#FFF",
    borderRadius: 15,
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: "#F0F4F8",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  cardTextContainer: { flex: 1 },
  cardTitulo: {
    fontSize: 16,
    fontFamily: "Merriweather_Bold",
    color: "#2D3748",
  },
  cardSubtitulo: {
    fontSize: 14,
    fontFamily: "Merriweather_Regular",
    color: "#718096",
    marginTop: 2,
  },

  // --- Estilos do Modal Exames ---
  modalOverlay: {
    flex: 1,
    backgroundColor: "#F0F4F8",
  },
  modalContent: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight + 10 : 40,
    paddingHorizontal: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 25,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  modalTitle: {
    fontSize: 22,
    fontFamily: "Merriweather_Bold",
    color: "#4A729A",
  },
  itemExameModal: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  tituloExameModal: {
    fontSize: 16,
    fontFamily: "Merriweather_Bold",
    color: "#2D3748",
  },
  dataExameModal: {
    fontSize: 14,
    fontFamily: "Merriweather_Regular",
    color: "#718096",
    marginTop: 2,
  },
  textoVazioModal: {
    textAlign: "center",
    marginTop: 40,
    color: "#A0AEC0",
    fontFamily: "Merriweather_Regular",
    fontSize: 16,
  },

  // ==========================================
  // --- ESTILOS DA IA HELI (BOTÃO E MODAL) ---
  // ==========================================
  fabHeli: {
    position: "absolute",
    bottom: 20,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#4A729A",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  modalContentHeli: {
    flex: 1,
    backgroundColor: "#F0F4F8",
    marginTop: Platform.OS === "android" ? StatusBar.currentHeight + 60 : 80,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  modalHeaderHeli: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  iconHeliContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#4A729A",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  modalTitleHeli: {
    fontSize: 20,
    fontFamily: "Merriweather_Bold", // 👈 Fonte integrada
    color: "#2D3748",
  },
  modalSubtitleHeli: {
    fontSize: 12,
    fontFamily: "Merriweather_Regular", // 👈 Fonte integrada
    color: "#718096",
  },
  chatAreaHeli: {
    flex: 1,
    marginBottom: 15,
  },
  balaoHeli: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 20,
    borderTopLeftRadius: 4,
    maxWidth: "85%",
    marginBottom: 10,
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  textoBalaoHeli: {
    fontSize: 14,
    fontFamily: "Merriweather_Regular", // 👈 Fonte integrada
    color: "#2D3748",
    lineHeight: 22,
  },
  inputContainerHeli: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    paddingHorizontal: 15,
    paddingVertical: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  inputHeli: {
    flex: 1,
    height: 40,
    fontFamily: "Merriweather_Regular", // 👈 Fonte integrada
    color: "#2D3748",
  },
  btnEnviarHeli: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#4A729A",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
  },
});
