import { Platform, StatusBar, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 30,
  },
  saudacao: {
    fontSize: 16,
    color: "#666666",
    marginBottom: 4,
  },
  nomeUsuario: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#4A729A",
  },
  perfilBotao: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",

    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  banner: {
    backgroundColor: "#4A729A",
    borderRadius: 20,
    padding: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 30,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  bannerTextContainer: {
    flex: 1,
    paddingRight: 16,
  },
  bannerTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 8,
  },
  bannerSubtitle: {
    color: "#E2E8F0",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  bannerButton: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  bannerButtonText: {
    color: "#4A729A",
    fontWeight: "bold",
    fontSize: 14,
  },
  bannerImagePlaceholder: {
    width: 80,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 16,
  },
  quickAccessRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 32,
  },
  quickAccessCard: {
    backgroundColor: "#FFFFFF",
    width: "30%",
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  quickAccessIconBox: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F0F4F8",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  quickAccessText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#4A729A",
  },
  historyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 30,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  historyType: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#4A729A",
  },
  historyDate: {
    fontSize: 12,
    color: "#999999",
    fontWeight: "500",
  },
  historyTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 4,
  },
  historySubtitle: {
    fontSize: 14,
    color: "#666666",
  },
  // Estilos do Card de Último Registro
  cardUltimo: {
    backgroundColor: "#FFF",
    borderRadius: 15,
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: "#F0F4F8",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  cardTextContainer: { flex: 1 },
  cardTitulo: { fontSize: 16, fontWeight: "bold", color: "#2D3748" },
  cardSubtitulo: { fontSize: 14, color: "#718096", marginTop: 2 },

  // Estilos do Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "#F0F4F8", // Fundo levemente opaco
  },
  modalContent: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight + 10 : 40,
    paddingHorizontal: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 25,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#4A729A",
  },
  itemExameModal: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF", // Card branco para os itens
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  tituloExameModal: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2D3748",
  },
  dataExameModal: {
    fontSize: 14,
    color: "#718096",
    marginTop: 2,
  },
  textoVazioModal: {
    textAlign: "center",
    marginTop: 40,
    color: "#A0AEC0",
    fontSize: 16,
  },
});
